export const AVAILABLE_COUNTRIES = [
  'China',
  'Italy',
  'Iran',
  'Spain',
  'Germany',
  'Korea, South',
  'France',
  'US',
  'Switzerland',
  'United Kingdom',
  'Netherlands',
  'Norway',
  'Austria',
  'Belgium',
  'Sweden',
  'Denmark',
  'Japan',
  'Cruise Ship',
  'Malaysia',
  'Canada',
  'Australia',
  'Portugal',
  'Qatar',
  'Czechia',
  'Greece',
  'Israel',
  'Brazil',
  'Finland',
  'Ireland',
  'Slovenia',
  'Singapore',
  'Iceland',
  'Bahrain',
  'Poland',
  'Pakistan',
  'Estonia',
  'Romania',
  'Chile',
  'Egypt',
  'Philippines',
  'Thailand',
  'Indonesia',
  'Saudi Arabia',
  'Iraq',
  'India',
  'Luxembourg',
  'Kuwait',
  'Lebanon',
  'San Marino',
  'Peru',
  'Russia',
  'United Arab Emirates',
  'Ecuador',
  'Turkey',
  'Slovakia',
  'South Africa',
  'Mexico',
  'Bulgaria',
  'Argentina',
  'Armenia',
  'Taiwan*',
  'Serbia',
  'Panama',
  'Croatia',
  'Vietnam',
  'Colombia',
  'Algeria',
  'Latvia',
  'Brunei',
  'Albania',
  'Hungary',
  'Costa Rica',
  'Cyprus',
  'Sri Lanka',
  'Morocco',
  'Jordan',
  'Andorra',
  'Malta',
  'Belarus',
  'Bosnia and Herzegovina',
  'Georgia',
  'Cambodia',
  'Venezuela',
  'Kazakhstan',
  'North Macedonia',
  'Moldova',
  'Uruguay',
  'Azerbaijan',
  'Senegal',
  'Lithuania',
  'Oman',
  'Tunisia',
  'Afghanistan',
  'Dominican Republic',
  'New Zealand',
  'Liechtenstein',
  'Guadeloupe',
  'Martinique',
  'Burkina Faso',
  'Ukraine',
  'Maldives',
  'Jamaica',
  'Bolivia',
  'French Guiana',
  'Uzbekistan',
  'Bangladesh',
  'Cameroon',
  'Reunion',
  'Paraguay',
  'Honduras',
  'Guyana',
  'Monaco',
  'Ghana',
  'Rwanda',
  'Guatemala',
  'Cuba',
  'Mongolia',
  'Guam',
  'Cote d`Ivoire',
  'Trinidad and Tobago',
  'Ethiopia',
  'Seychelles',
  'Kenya',
  'Mayotte',
  'Nigeria',
  'Congo (Kinshasa)',
  'Aruba',
  'Kosovo',
  'Montenegro',
  'Liberia',
  'Saint Lucia',
  'Barbados',
  'Namibia',
  'The Gambia',
  'Gambia',
  'Eswatini',
  'Nepal',
  'Greenland',
  'Mauritania',
  'Guinea',
  'Saint Vincent and the Grenadines',
  'Benin',
  'Gabon',
  'Congo (Brazzaville)',
  'Antigua and Barbuda',
  'Sudan',
  'Tanzania',
  'Suriname',
  'Somalia',
  'Central African Republic',
  'Bhutan',
  'Holy See',
  'Togo',
  'Equatorial Guinea',
  'The Bahamas'
]
